os: linux
language: java
jdk:
  - openjdk11

services:
  - postgresql

notifications:
  email: false

before_install:
  - chmod +x mvnw

addons:
  sonarcloud:
  organization: igorroncevic-1
  token: $SONAR_TOKEN

before_script:
  - psql -c 'create database pharmacydb;' -U postgres

script:
  - mvn clean install -DskipTests=false -B -V
  - mvn sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.organization=igorroncevic-1 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: isa-pharmacy-team18-backend
  on:
    branch: master

