os: linux
language: java
jdk:
  - openjdk11

services:
  - postgresql

notifications:
  email: false

before_install:
  - chmod +x mvnw

before_script:
  - psql -c 'create database pharmacydb;' -U postgres

script:
  - mvn install -DskipTests=false -Dmaven.javadoc.skip=true -B -V

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: isa-pharmacy-team18-backend
  on:
    branch: master

